[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    makuna/NeoPixelBus @ ^2.8.0
    mathertel/OneButton @ ^2.0.3
    electroniccats/MPU6050 @ ^1.0.2
